development:
  
  soundcloud:
    key: devkey
    secret: devsecret
    base_url: http://api.soundcloud.com
  
  twitter:
    key: devkey
    secret: devsecret
    base_url: https://twitter.com
  
  facebook:
    app_id: devappid
    secret: devsecret
    base_url: https://graph.facebook.com
    
  digg:
    key: devkey
    secret: devsecret
    base_url: http://digg.com
    
  myspace:
    key: 460993ec2a954a73b320482c7ba42243
    secret: b7802f2c44bc49f9ad95a6c019f29d1b444eae4c1cb043c6b8fcf1244e60cf37
    base_url: http://api.myspace.com

test:
  
  soundcloud:
    key: testkey
    secret: testsecret
    base_url: http://api.soundcloud.com
  
  twitter:
    key: testkey
    secret: testsecret
    base_url: https://twitter.com
  
  facebook:
    app_id: testappid
    secret: testsecret
    base_url: https://graph.facebook.com
    
  digg:
    key: testkey
    secret: testsecret
    base_url: http://digg.com

production:
  
  soundcloud:
    key: prokey
    secret: prosecret
    base_url: http://api.soundcloud.com
  
  twitter:
    key: prokey
    secret: prosecret
    base_url: https://twitter.com
  
  facebook:
    app_id: proappid
    secret: prosecret
    base_url: https://graph.facebook.com
    
  digg:
    key: prokey
    secret: prosecre
    base_url: http://digg.com    