# Promotion title, eg. Social to Download
title: Free <strong>Fucking</strong> Download

# Competition description
description: Tell your social friends about Scars on Broadway and get a free download.

# track url
track: http://soundcloud.com/leemartin/test

# These options customize certain aspects of the embedded SoundCloud player.
# http://wiki.github.com/soundcloud/Widget-JS-API/widget-options
player_params: "&color=000000&player_type=artwork&text_buy_track=Free Fucking Download"

# http://soundcloud.com/premium#premium-accounts
download_limit:

instructions: "Click below to share the track with your friends, plus get a free mp3 download."

facebook:
  header: Share
  status: "is listening to Scars on Broadway F*cking. Get yours http://bit.ly/abc"

twitter:
  header: Update Status
  status: "Scars on Broadway: Free F*cking Download http://bit.ly/123"
